# Generated by Django 2.2.6 on 2019-10-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='call_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
