# Generated by Django 2.2.6 on 2019-10-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='plb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
