# Generated by Django 2.2.6 on 2019-10-16 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_active'),
        ('travel', '0002_auto_20191015_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='entry_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_point', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='travel',
            name='exit_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_point', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='trip_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
