# Generated by Django 2.2.6 on 2019-10-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20191016_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='tracked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='exit_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
