# Generated by Django 2.2.6 on 2019-10-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_dayplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel'),
        ),
    ]
