# Generated by Django 2.2.6 on 2019-10-16 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0006_dayplan_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelUserUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('supervision', models.IntegerField(blank=True, null=True)),
                ('planning', models.IntegerField(blank=True, null=True)),
                ('contingency', models.IntegerField(blank=True, null=True)),
                ('comms', models.IntegerField(blank=True, null=True)),
                ('team_selection', models.IntegerField(blank=True, null=True)),
                ('fitness', models.IntegerField(blank=True, null=True)),
                ('env', models.IntegerField(blank=True, null=True)),
                ('complexity', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('fly_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fly_color', to='colors.Color')),
                ('pack_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_color', to='colors.Color')),
                ('tent_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tent_color', to='colors.Color')),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel')),
                ('traveler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
