# Generated by Django 2.2.6 on 2019-10-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_traveluserunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayplan',
            old_name='datetime',
            new_name='date',
        ),
    ]
