# Generated by Django 2.2.6 on 2019-10-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_active'),
        ('travel', '0008_auto_20191016_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayPlan',
            new_name='TravelDayPlan',
        ),
    ]
