# Generated by Django 2.2.6 on 2019-10-16 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('travel', '0009_auto_20191016_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle'),
        ),
    ]
