# Generated by Django 2.2.6 on 2019-10-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_travel_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='vehicle_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
