# Generated by Django 2.2.6 on 2019-10-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_travel_vehicle_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='bivy_gear',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='compass',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='first_aid_kit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='flagging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='flare',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='flashlight',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='gps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='head_lamp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='helmet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='ice_axe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='map',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='matches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='probe_pole',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='radio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='rope',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='shovel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='signal_mirror',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='space_blanket',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='spare_battery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='tent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='whistle',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
