# Generated by Django 2.2.6 on 2019-10-18 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20191017_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='days_of_food',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='off_trail_travel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='radio_monitor_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='weapon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TravelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel')),
            ],
        ),
    ]
