# Generated by Django 2.2.6 on 2019-10-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20191017_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='cell_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='satellite_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
