# Generated by Django 2.2.6 on 2019-10-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_auto_20191017_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelfile',
            name='name',
        ),
        migrations.AddField(
            model_name='travel',
            name='average_gar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='gar_mitigations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='mitigated_gar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='travel_files'),
        ),
    ]
