# Generated by Django 2.2.6 on 2019-10-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20191018_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='average_gar',
            new_name='gar_average',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='mitigated_gar',
            new_name='gar_mitigated',
        ),
    ]
