# Generated by Django 2.2.6 on 2019-10-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_auto_20191018_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='note',
            new_name='notes',
        ),
    ]
