# Generated by Django 2.2.6 on 2019-10-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_call_sign'),
        ('travel', '0017_auto_20191018_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='responsible_party',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
