# Generated by Django 2.2.6 on 2019-10-18 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_remove_traveluserunit_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='responsible_party',
            new_name='contacts',
        ),
    ]
