# Generated by Django 2.2.6 on 2019-10-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_auto_20191018_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
