# Generated by Django 2.2.6 on 2019-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_auto_20191020_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldayplan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='travelfile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='traveluserunit',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
