# Generated by Django 2.2.6 on 2019-10-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191020_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='kind',
            field=models.CharField(blank=True, choices=[('p', 'PEAK'), ('v', 'VALLEY'), ('rvr', 'RIVER'), ('lk', 'LAKE'), ('rdg', 'RIDGE'), ('th', 'TRAIL_HEAD'), ('m', 'MEADOW'), ('o', 'OTHER'), ('cg', 'CAMPGROUND'), ('b', 'BASIN'), ('a', 'AREA')], max_length=3, null=True),
        ),
    ]
